# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Build the TypeScript code into JavaScript
RUN npm run build

# Run the seed script
RUN npm run seed

# Expose the port the app runs on
EXPOSE 3000

# Start the app with nodemon in development mode
CMD ["npm", "start"]
